CREATE SEQUENCE IF NOT EXISTS revisions_seq
    INCREMENT 50
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

-- Table: public.revisions
-- DROP TABLE IF EXISTS public.revisions;
CREATE TABLE IF NOT EXISTS revisions
(
    id integer NOT NULL,
    "timestamp" bigint NOT NULL,
    actor character varying(255) NOT NULL,
    datetime timestamp(6) with time zone NOT NULL,
    CONSTRAINT revisions_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_rev_datetime
    ON revisions (datetime ASC NULLS LAST);

-- Table: public.employees
-- DROP TABLE IF EXISTS public.employees;
CREATE TABLE IF NOT EXISTS employees
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    version bigint NOT NULL,
    code character varying(10) NOT NULL,
    dob date NOT NULL,
    name character varying(50) NOT NULL,
    CONSTRAINT pkey_employees_id PRIMARY KEY (id),
    CONSTRAINT unq_employees_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS idx_employees_code
    ON employees (code ASC NULLS LAST);

-- Table: public.employees_aud
-- DROP TABLE IF EXISTS public.employees_aud;
CREATE TABLE IF NOT EXISTS employees_aud
(
    id bigint NOT NULL,
    rev integer NOT NULL,
    revtype smallint,
    code character varying(20),
    dob date,
    name character varying(50),
    CONSTRAINT pkey_employees_aud PRIMARY KEY (rev, id),
    CONSTRAINT fk_employees_aud_rev FOREIGN KEY (rev)
    REFERENCES revisions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);